# 1) Minimum level to show, plus the name of our logger/appender (LOG1)
log4j.rootLogger = INFO, LOG1

# 2) LOG1 writes to a FILE
log4j.appender.LOG1=org.apache.log4j.FileAppender

# 3) Where the file goes (a variable, then used with ${log})
log = ./logs/App/log4j
log4j.appender.LOG1.File=${log}/log.out

# 4) The format of each line
#%d	date/time	2026-09-30 12:00:00,123
#%p	priority (level)	INFO
#%t	thread	main
#%C	class	edu.spu...App
#%m	your message	Application is starting...
#%n	new line	
log4j.appender.LOG1.layout=org.apache.log4j.PatternLayout
log4j.appender.LOG1.layout.conversionPattern=%d %p [%t] %C - %m%n